--Script Miroslav Jiricek, Test for Informa
--Initiate Tables


--drop if necessary
  --DROP TABLE dbo.Student
  --DROP TABLE dbo.School
  --DROP TABLE dbo.Country

--COUNTRY
CREATE TABLE [dbo].[Country]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL
)
GO
--Sample autogenerated dataset: 100 countries
INSERT INTO dbo.Country([Name]) VALUES('Iraq'),('United Arab Emirates'),('France'),('Netherlands'),('Cook Islands'),('Djibouti'),('Sierra Leone'),('Costa Rica'),('Nepal'),('South Georgia and The South Sandwich Islands'),
									  ('Angola'),('Portugal'),('Niue'),('United States'),('Palestine, State of'),('Jersey'),('French Guiana'),('Algeria'),('United States'),('Angola'),
									  ('Saint Lucia'),('Pitcairn Islands'),('Moldova'),('Korea, South'),('Fiji'),('Reunion'),('Myanmar'),('Mauritania'),('Saint Pierre and Miquelon'),('Venezuela'),
									  ('Seychelles'),('Burkina Faso'),('Gabon'),('Cook Islands'),('Saint Pierre and Miquelon'),('Togo'),('Canada'),('Tuvalu'),('Saint Vincent and The Grenadines'),('Poland'),
									  ('Trinidad and Tobago'),('El Salvador'),('Heard Island and Mcdonald Islands'),('Palau'),('Nicaragua'),('Norfolk Island'),('Western Sahara'),('Samoa'),('Tokelau'),('Suriname'),
									  ('Cuba'),('Åland Islands'),('Micronesia'),('United States'),('Guatemala'),('Guadeloupe'),('Virgin Islands, British'),('Syria'),('Côte D''Ivoire (Ivory Coast)'),('Isle of Man'),
									  ('Grenada'),('Liechtenstein'),('French Guiana'),('Belarus'),('Andorra'),('San Marino'),('Italy'),('Slovakia'),('Saint Helena, Ascension and Tristan da Cunha'),('Panama'),
									  ('Malaysia'),('Cook Islands'),('Tunisia'),('Laos'),('Australia'),('Angola'),('Germany'),('Bahamas'),('Sudan'),('Germany'),
									  ('Norway'),('Zambia'),('Kuwait'),('Togo'),('Comoros'),('Burkina Faso'),('Swaziland'),('Suriname'),('Poland'),('Netherlands'),
									  ('Bhutan'),('Tuvalu'),('Guam'),('Kyrgyzstan'),('Russian Federation'),('Iran'),('Luxembourg'),('Kyrgyzstan'),('Namibia'),('Australia');

--SCHOOL
CREATE TABLE [dbo].[School]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Name] NVARCHAR(100) NOT NULL,
    [IdCountry] INT NOT NULL,
    CONSTRAINT [FK_IdCountry] FOREIGN KEY ([IdCountry]) REFERENCES [Country]([Id])
)
GO
--Sample autogenerated dataset: 100 schools for 20 countries
INSERT INTO dbo.School([Name],[IdCountry]) VALUES('Purus Duis Ltd',8),('Aliquet Diam Corp.',7),('Amet Associates',4),('Id Nunc Limited',15),('Fermentum Fermentum Consulting',19),('Sodales Purus Inc.',9),('Sed Libero Proin Institute',6),('Sed LLC',1),('Sodales Nisi Magna PC',6),('Sem Consequat Nec Industries',11),
										         ('Felis Industries',12),('Curabitur Inc.',13),('Arcu Eu Odio Corp.',16),('Eget Metus LLP',18),('Turpis Nulla Ltd',19),('Donec Egestas Aliquam Inc.',15),('Sem Institute',15),('Arcu Vestibulum Ante LLP',7),('Nulla Inc.',8),('Rutrum Corp.',15),
										         ('Aliquet Nec Imperdiet Limited',15),('Hendrerit Neque Foundation',15),('Ac Mattis Institute',12),('Sed Pharetra Corp.',9),('Scelerisque Neque Consulting',2),('In Hendrerit Consectetuer Associates',18),('Fusce Corporation',8),('Nullam Enim Ltd',12),('Curabitur LLP',14),('Vestibulum Accumsan Consulting',19),
										         ('Et Eros Limited',2),('Felis Nulla Associates',5),('Tincidunt PC',14),('Mi Institute',9),('Iaculis Quis Pede Consulting',14),('Quisque Ornare Foundation',3),('Ornare Corp.',7),('Elit Curabitur Sed Inc.',1),('Volutpat Nulla Ltd',11),('Suspendisse Sagittis Inc.',9),
										         ('Metus Facilisis Lorem LLC',16),('Molestie Corporation',1),('Sit Amet Dapibus Industries',13),('Magnis Dis Parturient Industries',17),('Feugiat Metus Corporation',1),('Dolor Dolor Corp.',6),('Ullamcorper Nisl Associates',2),('Sem PC',10),('Nisl LLP',9),('Nec Ligula LLP',1),
										         ('Ultrices Ltd',7),('Phasellus Industries',8),('Quis Lectus Nullam Industries',8),('Quisque Foundation',3),('Lorem LLP',19),('Eros Non Enim Institute',4),('Vitae Inc.',17),('Suspendisse Aliquet Company',7),('Nulla Inc.',20),('Dictum Proin Foundation',2),
										         ('At Arcu Vestibulum Associates',13),('Augue Ut LLC',1),('Tortor Integer Industries',5),('Non Institute',1),('Sagittis Duis Gravida LLC',20),('Dictum Foundation',19),('Nunc Institute',5),('Nec LLC',3),('Imperdiet Dictum Magna Incorporated',12),('Erat Etiam Limited',1),
										         ('Semper Pretium Ltd',8),('Suspendisse Tristique Limited',20),('Ac Fermentum Vel Consulting',12),('Vitae Risus Duis PC',10),('A Facilisis PC',9),('Cursus In Hendrerit Ltd',1),('Purus Ac PC',9),('Class Aptent Taciti Consulting',16),('Sollicitudin A Inc.',9),('Sed Congue Associates',16),
										         ('In Incorporated',2),('Orci Lacus Vestibulum Incorporated',11),('Iaculis Lacus Pede LLC',20),('Conubia Nostra Corporation',6),('Mattis Ltd',14),('Donec Limited',4),('Auctor Velit Company',19),('Et Rutrum Non Institute',8),('Nunc Ac Mattis Inc.',7),('Lacus PC',18),
										         ('Nibh Associates',8),('Enim Corp.',14),('Magna Sed Eu Corporation',12),('Aliquam Corporation',17),('Lorem Sit LLP',18),('Pede Sagittis Augue Associates',11),('Dolor Institute',13),('Netus Incorporated',19),('Magnis Dis Associates',14),('At Iaculis Quis Limited',19);


--STUDENT
CREATE TABLE [dbo].[Student]
(
    [IdentityCard] VARCHAR(15) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Surname] NVARCHAR(100) NOT NULL,
    [DateOfBirth] DATE NOT NULL,
	[IdSchool] INT NOT NULL,
	CONSTRAINT [FK_IdSchool] FOREIGN KEY ([IdSchool]) REFERENCES [School]([Id])
)
GO
--Sample autogenerated dataset: 100 students for 10 schools
INSERT INTO dbo.Student([IdentityCard],[Name],[Surname],[DateOfBirth],[IdSchool]) VALUES('1610050851599','Basia','Guy','1981-09-09T04:12:59-07:00',6),('1698013068199','Jonas','Travis','1976-11-06T12:36:53-08:00',9),('1658042940299','Malcolm','Hughes','1976-02-22T12:52:03-08:00',8),('1629060490499','Lillian','Dalton','1976-10-15T18:01:43-07:00',1),('1698022726299','Rhona','Rutledge','1990-03-20T13:44:47-08:00',10),('1657112430899','Zephania','Lowery','1978-11-10T05:00:19-08:00',5),('1682113005799','Ayanna','Coleman','1989-01-06T19:00:48-08:00',9),('1682021593999','Abdul','Fowler','1981-04-11T07:12:14-08:00',8),('1670021064999','Charde','Levy','1977-04-02T16:42:24-08:00',7),('1678070134699','Cyrus','Ortega','1977-08-22T04:23:57-07:00',2),
																						('1652081992399','Tarik','Kinney','1988-01-21T08:30:49-08:00',5),('1685032334999','Mufutau','Zamora','1985-08-28T15:47:06-07:00',1),('1610010757299','Adria','Pacheco','1985-03-05T22:32:42-08:00',2),('1641121649599','Lunea','Pope','1979-02-25T05:54:38-08:00',8),('1656041258299','Harrison','Leach','1977-10-25T18:30:13-07:00',4),('1656041842199','Jacqueline','Christian','1977-12-13T00:48:06-08:00',4),('1624080993799','Xanthus','Guerrero','1995-05-29T13:08:25-07:00',9),('1615092659599','Rafael','Rutledge','1988-07-19T08:37:18-07:00',8),('1611091713699','Gavin','Clay','1979-10-18T16:31:58-07:00',5),('1633030990499','Jescie','Ruiz','1975-10-29T07:21:20-08:00',2),
																						('1612030286399','Louis','Graham','1981-06-24T20:23:08-07:00',2),('1652073095999','Sebastian','Barnes','1995-01-24T19:02:21-08:00',10),('1622050290999','Brennan','Roberson','1976-03-14T11:13:23-08:00',8),('1686070665699','Ivory','Pierce','1976-03-24T11:53:55-08:00',5),('1660012188599','Kendall','Salazar','1986-05-22T08:34:04-07:00',10),('1645040341799','Nayda','Garcia','1976-09-22T09:39:28-07:00',8),('1664042716999','Yuri','Justice','1992-04-20T20:15:11-07:00',9),('1641021347799','Damon','Hopkins','1987-03-16T09:27:43-08:00',7),('1624022241399','Shelley','Goodman','1985-06-11T11:31:10-07:00',7),('1628022607699','Davis','Macias','1987-02-11T02:20:14-08:00',4),
																						('1676031631599','Channing','Carey','1976-02-10T13:39:03-08:00',7),('1647122726799','Malcolm','Chavez','1991-09-02T20:42:30-07:00',1),('1664030608399','Leilani','Floyd','1984-03-26T03:53:50-08:00',4),('1684041771699','Charissa','Daniels','1985-04-17T21:29:20-08:00',8),('1676020289199','Cooper','Duke','1990-08-18T10:24:34-07:00',10),('1677022845699','Ahmed','Pennington','1981-08-03T08:48:39-07:00',6),('1643112400599','Aidan','Rocha','1976-07-03T13:36:33-07:00',10),('1603033071899','Aretha','Miles','1988-03-11T20:23:28-08:00',5),('1609031589799','Penelope','Doyle','1987-11-08T21:52:29-08:00',1),('1648100976299','Amela','Morse','1982-09-23T20:11:27-07:00',10),
																						('1685071835199','Chancellor','Holland','1979-10-31T13:37:02-08:00',1),('1642012136999','Graham','Alexander','1994-09-24T03:48:21-07:00',6),('1624010601799','Meghan','Solomon','1992-04-17T20:59:28-07:00',4),('1619042608499','April','Estrada','1982-10-13T21:47:19-07:00',2),('1636011628099','Carissa','Meyer','1985-01-09T18:20:47-08:00',6),('1629123026799','Aidan','Curtis','1979-03-06T17:58:12-08:00',8),('1683082234999','Yardley','Copeland','1992-08-05T01:01:17-07:00',4),('1609012987499','Reese','Hurley','1986-11-12T22:50:21-08:00',8),('1607111309299','Pascale','Sims','1986-05-31T12:32:15-07:00',10),('1649010383099','Ariana','Dejesus','1980-03-28T00:28:42-08:00',2),
																						('1663012982999','Leroy','Howell','1982-11-28T20:29:37-08:00',10),('1657060581899','Barbara','Roach','1985-02-17T01:03:55-08:00',2),('1629032778899','Mercedes','Acosta','1989-06-15T18:55:16-07:00',7),('1672082066999','Lois','Hurst','1979-10-18T06:04:47-07:00',8),('1610021566499','Marcia','Dotson','1987-02-19T18:26:33-08:00',7),('1660060169999','Jayme','Olson','1979-08-19T07:28:46-07:00',8),('1691031054199','Wanda','Black','1982-06-11T02:13:22-07:00',9),('1651111373899','Bo','Dominguez','1985-03-18T14:10:58-08:00',8),('1615071923799','Whoopi','Chavez','1977-02-01T18:43:15-08:00',10),('1689051700999','Raphael','Miles','1995-02-15T11:19:47-08:00',8),
																						('1677022953799','Linda','Munoz','1976-09-19T15:40:18-07:00',7),('1613073041199','Marvin','Lott','1992-11-20T16:38:40-08:00',1),('1623031073199','Gabriel','Acosta','1986-02-10T22:51:09-08:00',1),('1611072330599','Dalton','Lawson','1979-10-07T14:56:12-07:00',2),('1665101609599','Trevor','Downs','1984-01-15T22:17:14-08:00',2),('1654070994599','Kirsten','Sargent','1980-01-01T00:34:59-08:00',3),('1643022688699','Alea','Hatfield','1986-01-11T18:10:02-08:00',3),('1672011425199','Violet','Austin','1994-08-27T16:50:09-07:00',5),('1698012545999','Sharon','Nieves','1989-04-29T14:52:55-07:00',2),('1656041073599','Keegan','Everett','1992-07-16T20:52:30-07:00',1),
																						('1687112345499','Debra','Stevenson','1986-03-11T17:49:08-08:00',6),('1680080622299','Dean','Swanson','1976-01-26T22:26:12-08:00',1),('1645112093699','Lacota','Hays','1980-02-13T03:34:39-08:00',4),('1648121199999','Jeremy','Horn','1989-05-17T22:56:41-07:00',7),('1607021645799','Lani','Terrell','1978-12-01T14:05:04-08:00',2),('1649012900499','Beck','Albert','1976-11-29T12:27:40-08:00',7),('1648022284499','Alexis','Taylor','1990-06-28T04:00:32-07:00',7),('1667031066699','Alexander','Carr','1994-12-30T11:42:20-08:00',2),('1669032122099','Hilel','Frank','1989-02-11T01:28:45-08:00',6),('1613081962399','Rhonda','Fisher','1994-10-30T20:26:42-08:00',3),
																						('1689070134099','Finn','Compton','1988-09-25T15:06:11-07:00',9),('1632111320499','Pandora','Mclean','1986-03-05T19:55:13-08:00',9),('1645091696399','Norman','Solis','1983-04-17T16:43:29-08:00',4),('1673022613599','Danielle','Hutchinson','1990-08-15T22:39:28-07:00',6),('1663041785699','Vernon','Powell','1995-02-17T23:20:11-08:00',8),('1637021701999','Phyllis','Rutledge','1990-05-09T17:04:17-07:00',2),('1604122556099','Blaine','Carver','1987-11-19T17:52:19-08:00',10),('1689102505899','Driscoll','Carr','1980-12-26T20:48:51-08:00',7),('1664062055499','Rafael','Shelton','1988-12-06T19:18:10-08:00',1),('1621022869999','Mari','Cline','1986-01-28T07:18:09-08:00',6),
																						('1684082206199','Melvin','Watkins','1992-03-13T22:49:28-08:00',5),('1695022664599','Keiko','Stafford','1982-12-07T18:32:59-08:00',7),('1645121154299','Barry','Vance','1979-03-06T04:51:53-08:00',4),('1678012337899','Lani','Pearson','1981-11-12T22:48:48-08:00',1),('1600052002399','Germaine','Spears','1995-02-27T17:26:24-08:00',10),('1679122203299','Igor','Bush','1982-06-24T15:02:42-07:00',10),('1644070666099','Amos','Shaffer','1984-10-04T21:16:27-07:00',5),('1660032196499','Stuart','Russell','1979-11-30T05:13:28-08:00',2),('1636022685999','Ivan','Mitchell','1980-04-25T08:29:21-08:00',4),('1651103029099','Sydney','Lott','1984-08-21T09:52:58-07:00',5);
