//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Students
    {
        public string Student_ID_card { get; set; }
        public string Name_and_Surname { get; set; }
        public string School_name { get; set; }
        public string Country_of_School { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
    }
}
